sudo: false
language: node_js
node_js:
 - 10 # use nodejs v10 LTS
cache: npm
branches:
 only:
  - master # build master branch only
script:
<<<<<<< HEAD
  - hexo clean
  - hexo generate
deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GH_TOKEN
 keep-history: true
 on:
  branch: master
 local-dir: public
=======
  - hexo g
  - hexo d
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
>>>>>>> 968293871593fe3e02e289d3f28ae46a06954111
