# 指定语言环境
language: node_js

# 指定node_js版本
node_js:
 - "10"

branches:
 only:
  - master

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
# before_install:
#  - git config user.name "gaona233"
#  - git config user.email "1064193183@qq.com"

# Start: Build Lifecycle
install:
 - npm install -g hexo-cli
 - npm install

# 执行清缓存，生成网页操作
script:
 - hexo clean
 - hexo generate
 - npm run deploy
